--ConVar syncing
CreateConVar("ttt2_cursed_affect_det", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_damage_immunity", "0", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_seconds_until_respawn", "10", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_respawn_at_mapspawn", "0", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_tag_dist", "150", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_backsies_timer", "0", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_no_dmg_backsies", "0", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_self_immolate_mode", "2", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_speed_multi", "1.2", {FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_stamina_regen", "1.0", {FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_REPLICATED})
CreateConVar("ttt2_cursed_stamina_drain", "0.35", {FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_REPLICATED})
CreateConVar("ttt2_role_swap_deagle_enable", "1", {FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_REPLICATED})
CreateConVar("ttt2_role_swap_deagle_refill_time", "30", {FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_REPLICATED})
